name: Docker check when updating docker file

on:
  pull_request:
    paths:
        - 'Dockerfile'
    branches: [ "master" ]

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Docker build
      run: |
        docker build .
        if [ $? -ne 0 ]; then
          echo "Docker build failed"
          exit 1 
        fi