name: App Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  UBUNTU_VERSION: 22.04

jobs:
  build:
    runs-on: ubuntu-${{ env.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Boost
      uses: MarkusJx/install-boost@v2.4.5
      with:
        boost_version: 1.74.0
        platform_version: ${{ env.UBUNTU_VERSION }}
    - name: Generate CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build project
      run: cmake --build ${{github.workspace}}/build
