name: App Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Docker version
      run: docker --version
    - name: Docker build
      run: |
        docker build -t project .
        if [ $? -ne 0 ]; then
          echo "Docker build failed"
          exit 1 
        fi
    - name: Build project
      run: |
        docker run --rm project bash -c "\
          mkdir -p build && \
          cd build && \
          cmake .. && \
          make"
        if [ $? -ne 0 ]; then
          echo "Build project failed"
          exit 1
        fi