name: App Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Boost
      run: apt-get update && apt-get install -y libboost-all-dev
    - name: Generate CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build project
      run: cmake --build ${{github.workspace}}/build
