name: App Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Boost
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.74.0
        libraries: thread
    - name: Generate CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_PREFIX_PATH=${{ runner.workspace }}/boost
    - name: Build project
      run: cmake --build ${{github.workspace}}/build
