name: App Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Docker version
      run: docker --version
    - name: Docker build
      run: |
        docker build -t app .
        if [ $? -ne 0 ]; then
          echo "Docker build failed"
          exit 1 
        fi