name: App Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Docker:
      run: docker --version
    - name: Install Boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
    - name: Generate CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build project
      run: cmake --build ${{github.workspace}}/build
